### ISSUE TITLE
No success indicator on successful 'Send to Oracle Explorer' button click

### ISSUE THREAD

**Issue by phjlljp** [bitcoin-s/krystal-bull#58]
The  'Send to Oracle Explorer' button does not give any indication that it has worked, so users will click it repeatedly. This could spam the Oracle Explorer. 

![image](https://user-images.githubusercontent.com/76761332/118105053-c5cad900-b390-11eb-934c-b8a0cfdf5184.png)

**Comment by benthecarman** [comment]
closed by #69
