### ISSUE TITLE
Clicking on link produce by krystal bull does not take me to the oracle explorer

### ISSUE THREAD

**Issue by Christewart** [bitcoin-s/krystal-bull#71]
It does not seem to take me to the web page, here is the link to the actual event, but i had to manually go to it

https://oracle.suredbits.com/announcement/9cd4f6d7b190d16be2a8a57514edfddc077f80c09f585c74f8c27e908076096b

<img width="540" alt="Screen Shot 2021-06-23 at 12 18 07 PM" src="https://user-images.githubusercontent.com/3514957/123140600-1700ca80-d41d-11eb-8e74-b63944ec3776.png">

**Comment by benthecarman** [comment]
This is using ScalaFX's `HyperLink` tool, may be a bug with it, but will look into it

**Comment by Christewart** [comment]
Same thing applies when submitting fresh announcements, it seems to work but the link doesn't. Here is the announcement i had to manually navigate to on the explorer

https://oracle.suredbits.com/announcement/fec801e24dd1c07722cdc1f14a33c6519b719eef534373788878b3854a0a4dfa
